### PR TITLE
CDP-615: Update languages property to match schema for translated posts

### PR DESCRIPTION
**Pull request by bit-saver**
Added a function for grabbing all of the post translations from the WPML translation table.
The function then calls another added function that tries to match the language code to a CDP locale or code (if no locale match).
Translated posts will now match the current schema.

### CODE REVIEW

**Comment by sc0ttius** [comment]
Should we account for whether the translated posts are both published and set to index to CDP?

**Comment by bit-saver** [comment]
Oof, that's probably a good idea.

**Comment by bit-saver** [comment]
Pushed.

**Comment by sc0ttius** [comment]
For the sync status, if it is an initial sync, the value may be empty. Should we filter against only those posts with an explicit setting of 'no' due to the fact the CDP sync setting is opt-out and not opt-in?

**Comment by bit-saver** [comment]
Ah you're right.  Good call.  Changing now.

**Pull request merged**
